# Generated by Django 4.2.18 on 2025-02-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('region', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
